apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 6 
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest 
        ports:
        - containerPort: 80 
