
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 6 # Set the desired number of replicas

  # Define the pod template for replicas
  template:
    metadata:
      labels:
        app: nginx # Labels for pods managed by deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      
