apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-pod
spec:
  replicas: 4  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
