
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  replicas: 4  # Deploy four replicas for high availability
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      initContainers:
      - name: init-mysql
        image: busybox:latest
        command: ['sh', '-c', 'sleep 10 && mysqld --initialize-insecure']
      volumeClaimTemplates:
      - metadata:
          name: mysql-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi  # Adjust storage request based on your needs
          persistentVolumeClaim:
            claimName: mysql-pvc
