apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  replicas: 4  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
